image:
  name: alpine:latest
stages:
  - build
before_script:
  - mkdir -p ~/.ssh
  - "which ssh-agent || ( apk add openssh )"
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh-add -l # This will list all the loaded keys
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
build:development:
  stage: build
  only:
    - main
  script:
    - echo "Build starting.."
    - apk update
    - apk add rsync
    - rsync --version
    - rsync -av -r ./* ubuntu@54.165.107.96:server/deploy_test
    - ssh -v ubuntu@54.165.107.96 'cd "server/deploy_test" && DOCKER_NETWORK_ALIAS=deploy_test DOCKER_ENV_FILE=/root/deploy_test/env.d/.env.api docker compose --env-file /root/deploy_test/env.d/.env.api  -f ./docker-compose.dev.yml up --build -d'
